image:
  file: .gitpod.Dockerfile

tasks:
  - init: lua -v && luarocks --version && echo 'Lua is Installed Sucessfully'

vscode:
  extensions:
    - ms-python.python
    - crystal-lang-tools.crystal-lang
    - Dart-Code.dart-code
    - PKief.material-icon-theme
    - sumneko.lua
    - rebornix.ruby
    - wingrunr21.vscode-ruby
    - kaiwood.endwise
